// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: proto/paste.proto

package paste

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PasteService_GetPaste_FullMethodName = "/paste.PasteService/GetPaste"
)

// PasteServiceClient is the client API for PasteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PasteServiceClient interface {
	GetPaste(ctx context.Context, in *PasteId, opts ...grpc.CallOption) (*Paste, error)
}

type pasteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPasteServiceClient(cc grpc.ClientConnInterface) PasteServiceClient {
	return &pasteServiceClient{cc}
}

func (c *pasteServiceClient) GetPaste(ctx context.Context, in *PasteId, opts ...grpc.CallOption) (*Paste, error) {
	out := new(Paste)
	err := c.cc.Invoke(ctx, PasteService_GetPaste_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PasteServiceServer is the server API for PasteService service.
// All implementations must embed UnimplementedPasteServiceServer
// for forward compatibility
type PasteServiceServer interface {
	GetPaste(context.Context, *PasteId) (*Paste, error)
	mustEmbedUnimplementedPasteServiceServer()
}

// UnimplementedPasteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPasteServiceServer struct {
}

func (UnimplementedPasteServiceServer) GetPaste(context.Context, *PasteId) (*Paste, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPaste not implemented")
}
func (UnimplementedPasteServiceServer) mustEmbedUnimplementedPasteServiceServer() {}

// UnsafePasteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PasteServiceServer will
// result in compilation errors.
type UnsafePasteServiceServer interface {
	mustEmbedUnimplementedPasteServiceServer()
}

func RegisterPasteServiceServer(s grpc.ServiceRegistrar, srv PasteServiceServer) {
	s.RegisterService(&PasteService_ServiceDesc, srv)
}

func _PasteService_GetPaste_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PasteId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasteServiceServer).GetPaste(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PasteService_GetPaste_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasteServiceServer).GetPaste(ctx, req.(*PasteId))
	}
	return interceptor(ctx, in, info, handler)
}

// PasteService_ServiceDesc is the grpc.ServiceDesc for PasteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PasteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paste.PasteService",
	HandlerType: (*PasteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPaste",
			Handler:    _PasteService_GetPaste_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/paste.proto",
}
