name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Prepare local repository
        uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags -f
      - 
        name: semver-releaser
        uses: heyvito/semver-releaser@v0.0.10
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}